apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "air-helm.fullname" . }}-config
  labels:
    {{- include "air-helm.labels" . | nindent 4 }}
data:
  air.toml: |-
    {{- if .Values.airServer.config }}
    {{ .Values.airServer.config | indent 4 }}
    {{- else }}
    root = "/app"
    testdata_dir = "testdata"
    tmp_dir = "tmp"

    [build]
      args_bin = []
      bin = "/app/tmp/{{ .Release.Name }}"
      cmd = "go -C /app/source/{{ .Values.airServer.code.modulePath }} build -o /app/tmp/{{ .Release.Name }} {{ .Values.airServer.code.buildSource }}"
      delay = 0
      exclude_dir = ["assets", "tmp", "vendor", "testdata"]
      exclude_file = []
      exclude_regex = ["_test.go"]
      exclude_unchanged = false
      follow_symlink = false
      full_bin = ""
      include_dir = []
      include_ext = ["go", "tpl", "tmpl", "html"]
      include_file = []
      kill_delay = "0s"
      log = "build-errors.log"
      poll = false
      poll_interval = 0
      rerun = false
      rerun_delay = 500
      send_interrupt = false
      stop_on_error = false

    [color]
      app = ""
      build = "yellow"
      main = "magenta"
      runner = "green"
      watcher = "cyan"

    [log]
      main_only = false
      time = false

    [misc]
      clean_on_exit = false

    [screen]
      clear_on_rebuild = false
      keep_scroll = true
    {{- end }}
