apiVersion: v1
kind: Service
metadata:
  name: {{ include "air-helm.fullname" . }}
  labels:
    {{- include "air-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.http.enabled }}
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
    {{- end }}
    {{- if .Values.service.grpc.enabled }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
    {{- end }}
  selector:
    {{- include "air-helm.selectorLabels" . | nindent 4 }}
